require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  
  Exclude:
    - 'db/**/*.rb'
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/MixinUsage:
  Exclude:
    - 'bin/**/*'

Metrics/MethodLength:
  Max: 11

Rails/FilePath:
  Exclude:
    - 'config/environments/development.rb'
