require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.1

  SuggestExtensions: false
  Exclude:
    - 'db/**/*.rb'
    - 'vendor/**/*'
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/MixinUsage:
  Exclude:
    - 'bin/**/*'

Lint/DuplicateBranch:
  Exclude:
    - 'lib/tasks/music.rake'

Metrics/MethodLength:
  Max: 11

Rails/FilePath:
  Exclude:
    - 'config/environments/development.rb'
