---
version: 2.1
orbs:
  ruby: circleci/ruby@2.0.0
jobs:
  build:
    parameters:
      ruby-version:
        description: "Ruby version"
        default: "2.7.6"
        type: "string"
    docker:
      - image: 'cimg/ruby:<< parameters.ruby-version >>-browsers'
    steps:
      - checkout
      - ruby/install-deps:
        key: gems-v1-<< parameters.ruby-version >>
  checking:
    docker:
      - image: 'cimg/ruby:3.0.0'
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
  test:
    parameters:
      ruby-version:
        description: "Ruby version"
        default: "2.7.6"
        type: "string"
    docker:
      - image: 'cimg/ruby:<< parameters.ruby-version >>-browsers'
      - environment:
          POSTGRES_DB: geaccirc_test
          POSTGRES_USER: geaccirc
          POSTGRES_HOST_AUTH_METHOD: trust
        image: 'cimg/postgres:10.22'
    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      PGHOST: 127.0.0.1
      PGUSER: geaccirc
      RAILS_ENV: test
    parallelism: 3
    steps:
      - checkout
      - ruby/install-deps:
        key: gems-v1-<< parameters.ruby-version >>
      - run:
          command: 'dockerize -wait tcp://localhost:5432 -timeout 1m'
          name: Wait for DB
      - run:
          command: 'bundle exec rails db:schema:load --trace'
          name: Database setup
      - ruby/rspec-test:
          include: spec/**/*_spec.rb
workflows:
  build_and_test:
    jobs:
      - build:
          name: build-v<< matrix.ruby-version >>
          matrix:
            parameters:
              ruby-version: ["2.7.6", "3.0.0"]
      - checking
      - test:
          requires:
            - build-v<< matrix.ruby-version >>
          matrix:
            parameters:
              ruby-version: ["2.7.6", "3.0.0"]
