---
version: 2.1
commands:
 install_dependencies:
    steps:
      - run: gem install bundler -v '2.4.19'
      - run: cp Gemfile.lock Gemfile.lock.bak
      - restore_cache:
          key: &gem_key ceaccirc-{{ checksum "Gemfile.lock.bak" }}
      - run: bundle install --path ./vendor/bundle
      - save_cache:
          key: *gem_key
          paths:
            - ./vendor/bundle
      - restore_cache:
          name: Restore Yarn Package Cache
          key: &yarn_key geaccirc-cimg-{{ checksum "yarn.lock" }}
      - run:
          name: Install NPM Dependencies via Yarn
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: *yarn_key
          paths:
            - ~/.cache/yarn
orbs:
  ruby: circleci/ruby@2.1.0
jobs:
  build:
    parameters:
      ruby-version:
        description: "Ruby version"
        default: "3.1.4"
        type: "string"
    docker:
      - image: 'cimg/ruby:<< parameters.ruby-version >>-browsers'
    steps:
      - checkout
      - install_dependencies
  rubocop:
    docker:
      - image: 'cimg/ruby:3.1.4'
    steps:
      - checkout
      - install_dependencies
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
  test:
    parameters:
      ruby-version:
        description: "Ruby version"
        default: "3.1.4"
        type: "string"
    docker:
      - image: 'cimg/ruby:<< parameters.ruby-version >>-browsers'
      - environment:
          POSTGRES_DB: geaccirc_test
          POSTGRES_USER: geaccirc
          POSTGRES_HOST_AUTH_METHOD: trust
        image: 'cimg/postgres:10.22'
    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      PGHOST: 127.0.0.1
      PGUSER: geaccirc
      RAILS_ENV: test
    parallelism: 3
    steps:
      - checkout
      - install_dependencies
      - run:
          command: 'dockerize -wait tcp://localhost:5432 -timeout 1m'
          name: Wait for DB
      - run:
          command: 'bundle exec rails db:schema:load --trace'
          name: Database setup
      - ruby/rspec-test:
          include: spec/**/*_spec.rb
workflows:
  build_and_test:
    jobs:
      - build:
          name: build-v<< matrix.ruby-version >>
          matrix:
            parameters:
              ruby-version: ["3.1.4"]
      - rubocop
      - test:
          requires:
            - build-v<< matrix.ruby-version >>
          matrix:
            parameters:
              ruby-version: ["3.1.4"]
